-- AlterTable
ALTER TABLE "task" ALTER COLUMN "workerName" DROP NOT NULL,
ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "deadlineAt" DROP NOT NULL,
ALTER COLUMN "workerId" DROP NOT NULL;
